### ISSUE TITLE
Trying to run this but

### ISSUE THREAD

**Issue by ghost** [gehrhorn/nessus-analyzer#1]
`./nessus-analyzer.rb -f chi.nessus --show-statistics 
./nessus-analyzer.rb:226:in `process_nessus_file': uninitialized constant Nessus::Parse (NameError)
Did you mean?  Parts
	from ./nessus-analyzer.rb:291:in `<main>'`

Any ideas?

**Comment by gehrhorn** [comment]
Can you send me a test nessus file? I don't have one and I don't use nessus regularly.

**Comment by gehrhorn** [comment]
Also @tomboxme can you list the output of ```gem list```

**Comment by ghost** [comment]
Managed to solve, ended up just being some odd ruby version in my path. 

export PATH=/usr/bin:/bin:/usr/local/bin
export GEM_PATH=/usr/lib64/ruby/gems/2.3.0/
export GEM_HOME=/usr/lib64/ruby/gems/2.3.0/

Thank you!
